<a href="https://colab.research.google.com/github/mpradiptanugroho2020-ops/221230031-Pengantar-ML/blob/main/week-02/latihan-praktikum-2-numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

'''TODO: Implementasi Preprocessing Pipeline'''
# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Mean=5, Std=10

# ✅ TODO 1: Normalisasi Z-score: (x - mean) / std
def z_score_normalization(data):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    std[std == 0] = 1
    return (data - mean) / std

X_normalized = z_score_normalization(X)

# ✅ TODO 2: Handle outliers - replace values beyond 3 std with boundaries
def handle_outliers(data, std_threshold=3):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    upper_bound = mean + std_threshold * std
    lower_bound = mean - std_threshold * std

    data_clipped = np.clip(data, lower_bound, upper_bound)
    return data_clipped

X_cleaned = handle_outliers(X_normalized)

# ✅ TODO 3: One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    n_classes = np.max(labels) + 1
    one_hot = np.zeros((labels.size, n_classes))
    one_hot[np.arange(labels.size), labels] = 1
    return one_hot

labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

# ✅ TODO 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.2):
    n_samples = X.shape[0]
    n_test = int(n_samples * test_size)
    indices = np.arange(n_samples)
    np.random.shuffle(indices)

    test_idx = indices[:n_test]
    train_idx = indices[n_test:]

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split_numpy(X, np.random.randint(0, 3, 100))

# ✅ Check hasil
assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(), 1, atol=1e-10), "Std should be ~1 after z-score"
print("✅ NumPy operations completed successfully")
import numpy as np

'''TODO: Implementasi Preprocessing Pipeline'''
# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5  # Mean=5, Std=10

# ✅ TODO 1: Normalisasi Z-score: (x - mean) / std
def z_score_normalization(data):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    std[std == 0] = 1
    return (data - mean) / std

X_normalized = z_score_normalization(X)

# ✅ TODO 2: Handle outliers - replace values beyond 3 std with boundaries
def handle_outliers(data, std_threshold=3):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)
    upper_bound = mean + std_threshold * std
    lower_bound = mean - std_threshold * std
    data_clipped = np.clip(data, lower_bound, upper_bound)
    return data_clipped

X_cleaned = handle_outliers(X_normalized)

# ✅ TODO 3: One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    n_classes = np.max(labels) + 1
    one_hot = np.zeros((labels.size, n_classes))
    one_hot[np.arange(labels.size), labels] = 1
    return one_hot

labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

# ✅ TODO 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.2):
    n_samples = X.shape[0]
    n_test = int(n_samples * test_size)
    indices = np.arange(n_samples)
    np.random.shuffle(indices)

    test_idx = indices[:n_test]
    train_idx = indices[n_test:]

    X_train, X_test = X[train_idx], X[test_idx]
    y_train, y_test = y[train_idx], y[test_idx]

    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split_numpy(X, np.random.randint(0, 3, 100))

# ✅ Check hasil
assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(), 1, atol=1e-10), "Std should be ~1 after z-score"
print("✅ NumPy operations completed successfully")

print("Original Data (first 5 samples):")
print(X[:5])

print("After Z-score Normalization (first 5 samples):")
print(X_normalized[:5])

print("After Outlier Handling (first 5 samples):")
print(X_cleaned[:5])

print("One-hot Encoding Result:")
print("Labels:", labels)
print(one_hot_labels)

print("Train-Test Split Result:")
print(f"   X_train shape: {X_train.shape}")
print(f"   X_test shape : {X_test.shape}")
print(f"   y_train shape: {y_train.shape}")
print(f"   y_test shape : {y_test.shape}")


✅ NumPy operations completed successfully
✅ NumPy operations completed successfully
Original Data (first 5 samples):
[[  9.96714153   3.61735699  11.47688538  20.23029856   2.65846625]
 [  2.65863043  20.79212816  12.67434729   0.30525614  10.42560044]
 [  0.36582307   0.34270246   7.41962272 -14.13280245 -12.24917833]
 [ -0.62287529  -5.1283112    8.14247333  -4.08024076  -9.12303701]
 [ 19.65648769   2.742237     5.67528205  -9.24748186  -0.44382725]]
After Z-score Normalization (first 5 samples):
[[ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
 [-0.21141045  1.53420502  0.87977344 -0.62585547  0.53845484]
 [-0.46735006 -0.55422449  0.34303561 -2.13809665 -1.58578836]
 [-0.57771567 -1.1129603   0.41687036 -1.08519209 -1.2929218 ]
 [ 1.68601234 -0.30916828  0.16486193 -1.62640854 -0.47982667]]
After Outlier Handling (first 5 samples):
[[ 0.604418   -0.21979528  0.75746006  1.461092   -0.18919425]
 [-0.21141045  1.53420502  0.87977344 -0.62585547  0.53845484]
 [-0.467350