<a href="https://colab.research.google.com/github/mpradiptanugroho2020-ops/221230031-Pengantar-ML/blob/main/week-02/latihan-praktikum-4-pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

'''TODO: Implementasi Operasi Dasar Neural Networks'''
# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)
bias = torch.randn(1)

# ✅ TODO 1: Implementasi linear layer manual: y = XW + b
def linear_layer(X, W, b):
    return torch.matmul(X, W) + b  # Linear transformation

output = linear_layer(X, weights, bias)

# ✅ TODO 2: Implementasi ReLU activation function
def relu_activation(tensor):
    return torch.maximum(tensor, torch.tensor(0.0))  # Element-wise max(0, x)

activated = relu_activation(output)

# ✅ TODO 3: Batch normalization sederhana
def simple_batch_norm(tensor, epsilon=1e-5):
    mean = tensor.mean(dim=0, keepdim=True)
    std = tensor.std(dim=0, keepdim=True)
    normalized = (tensor - mean) / (std + epsilon)
    return normalized

normalized = simple_batch_norm(X)

# ✅ TODO 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    one_hot = torch.zeros(labels.size(0), num_classes)
    one_hot[torch.arange(labels.size(0)), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)

# ✅ Assertions
assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"

### BONUS: ADVANCED TENSOR OPERATIONS ###

'''TODO: Matrix Multiplication dari Prinsip Dasar'''
def manual_matrix_multiply(A, B):
    """
    Implementasi perkalian matriks manual tanpa torch.matmul
    """
    rows_A, cols_A = A.shape
    rows_B, cols_B = B.shape
    assert cols_A == rows_B, "Matrix dimensions incompatible"

    result = torch.zeros(rows_A, cols_B)
    for i in range(rows_A):
        for j in range(cols_B):
            result[i, j] = torch.sum(A[i, :] * B[:, j])
    return result

# Test dengan matriks kecil
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"


print("✅ PyTorch operations completed\n")

print("1Linear layer output (y = XW + b):")
print(output[:5])

print("After ReLU activation:")
print(activated[:5])

print("Normalized input (batch norm, first 5 rows):")
print(normalized[:5])

print("One-hot encoding result:")
print("Labels:", labels.tolist())
print(one_hot)

print("Advanced tensor operations completed successfully")

print("Manual matrix multiplication result:")
print(manual_result)

print("Torch matmul result (for comparison):")
print(torch_result)


✅ PyTorch operations completed

1Linear layer output (y = XW + b):
tensor([[-7.0234],
        [ 3.7311],
        [-7.6301],
        [10.2620],
        [ 0.3299]])
After ReLU activation:
tensor([[ 0.0000],
        [ 3.7311],
        [ 0.0000],
        [10.2620],
        [ 0.3299]])
Normalized input (batch norm, first 5 rows):
tensor([[ 7.5580e-01,  3.8172e-01,  1.8655e-03,  2.5784e+00, -1.3380e+00,
          8.6641e-01,  1.1409e-01, -6.7233e-02,  7.9975e-01, -7.3008e-01],
        [-4.9321e-01,  1.0234e+00,  4.8977e-01, -4.9020e-01,  1.0669e+00,
         -1.1059e-01, -1.5537e+00, -6.8912e-02, -1.1503e+00, -2.3473e-01],
        [ 2.2167e+00,  9.6231e-01,  2.8972e+00, -7.6612e-02, -2.9919e-01,
          1.3901e+00,  1.1174e+00,  8.5983e-03,  2.1626e-01,  7.9240e-01],
        [-7.6246e-01,  4.5537e-01,  8.7955e-02, -8.6798e-01,  1.5683e+00,
         -7.1150e-01, -6.7330e-01, -2.4535e+00, -5.5311e-01,  1.6939e+00],
        [-1.7859e+00, -5.7471e-01,  2.1214e-01, -1.0151e+00, -1.6241e+00,
   